### PR TITLE
Update hdel method to support deleting multiple hash fields

### PR DESCRIPTION
**Pull request by asilgalis**
Update `hdel` method to support deleting multiple hash fields.

Reference: redis command [HDEL](https://redis.io/commands/hdel).

### CODE REVIEW

**Comment by omansour** [comment]
test arent working :( 
no ideas why ...

**Comment by asilgalis** [comment]
I have just updated one method by enabling feature to reflect redis functionality which was not implemented.

Well it is very clear why tests are not working, you need to update your dependencies:

```
Your requirements could not be resolved to an installable set of packages.
  Problem 1
    - Root composer.json requires atoum/atoum master-dev -> satisfiable by atoum/atoum[dev-master].
    - atoum/atoum dev-master requires php ^7.2 || ^8.0 -> your php version (7.1.27) does not satisfy that requirement.

```

Details (see https://travis-ci.org/github/M6Web/RedisMock/builds/745402043):

- Job with php 7.1 will not work as you need to lock **atoum/atoum** to the version that requires php 7.1 and of course split to the separate branch something like **5.x** (unless you don't want to continue support for older php versions) and tag with **5.0.1**.
- Jobs with php 7.2 and 7.3 will not work because **atoum/atoum** introduced breaking changes (namespaces have changed and more) but your library still depends on **dev-master** and tag with **6.0.0**.

**Comment by asilgalis** [comment]
Fixed broken namespaces and stuff

**Review by Oliboy50 — APPROVED** [review]

**Review by lnahiro — APPROVED** [review]

**Review by jdecool — APPROVED** [review]

**Comment by lnahiro** [comment]
Hello @asilgalis, 
can you rebase your branch with master ? i just updated to fix the ci. thank you

**Comment by lnahiro** [comment]
Added in release : [v5.1.0](https://github.com/BedrockStreaming/RedisMock/releases/tag/v5.1.0)

**Pull request merged**
